services:
  redis:
    image: redis:5.0.10
    ports:
      - "6379:6379"
    restart: always

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 0425
      MYSQL_DATABASE: nowcoder
      MYSQL_USER: nowcoder
      MYSQL_PASSWORD: nowcoder
    ports:
      - "3306:3306"
    restart: always

  elasticsearch:
    image: elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always

  zookeeper:
    image: zookeeper:3.7
    ports:
      - "2181:2181"
    restart: always

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    restart: always

#  wkhtmltopdf:
#    image: ghcr.io/puppeteer/wkhtmltopdf:latest
#    ports:
#      - "8080:8080"
#    restart: always

  wkhtmltopdf:
    image: interns/wkhtmltopdf:latest
    ports:
      - "8080:80"
    restart: always

#复制文件到docker容器里
#  docker cp "D:\java_idea\nklt\src\main\resources\community-init-sql-1.5\init_data.sql" yue_mysql:/tmp/init_data.sql


